'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "../../components/Navbar"
import ScrollAwareFooter from '../../components/ScrollAwareFooter'
import { LogGoodProvider } from '/components/LogGoodContext';
import { UserContextProvider } from '../../components/UserContext';


//In next Js, the layout.js file takes the place that the app file took in 
//normal React. So components imported here will appear on every page. 


const inter = Inter({ subsets: ['latin'] })

export const metadata  = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <LogGoodProvider>
      <UserContextProvider>
      <body className={inter.className}>
      <Navbar/>
      <div className="page-wrapper">
      <div className='content'>
        {children}
        </div>
        <div className="filler"></div>
        <ScrollAwareFooter/></div>
        </body>
        </UserContextProvider>
        </LogGoodProvider>
    </html>
  )
}
