'use client';
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "../../components/Navbar"
import ScrollAwareFooter from '../../components/ScrollAwareFooter'
import { LogGoodProvider } from '/components/LogGoodContext';
import { UserContextProvider } from '../../components/UserContext';
import { JwtContextProvider } from '../../components/JwtContext';


//In next Js, the layout.js  components imported here will appear on every page. 


const inter = Inter({ subsets: ['latin'] })

export const metadata  = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Space+Mono&display=swap" rel="stylesheet"></link>
      <LogGoodProvider>
      <UserContextProvider>
      <JwtContextProvider>
      <body className={inter.className}>
      <Navbar/>
      <div className="page-wrapper">
      <div className='content'>
        {children}
        </div>
        <div className="filler"></div>
        <ScrollAwareFooter/></div>
        </body>
        </JwtContextProvider>
        </UserContextProvider>
        </LogGoodProvider>
    </html>
  )
}
